sudo: required
language: node_js
node_js:
  - "6"
env:
  NO_SECURITY=1
  
services:
  - docker

before_install:
  - docker pull influxdb
  - docker run -d -p 8083:8083 -p 8086:8086  influxdb
  - docker ps


